import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/owned/header";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/owned/Footer";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/owned/DisableDraftmode";
import { VisualEditing } from "next-sanity";
import { SanityLive } from "@/sanity/lib/live";

const poppins = localFont({
  src:"../../fonts/poppins.woff2",
  variable:"--font-poppins",
  weight:'400',
  preload:false
})






export const metadata: Metadata = {
  title: "BlueBerry",
  description: "Generated by BlueBerry Team",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>

    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {(await draftMode()).isEnabled &&(
          <>
          <DisableDraftMode/>
          <VisualEditing/>
          </>
        )}
        <Header/>
        {children}
        <Footer/>
        <Toaster
        position="bottom-right"
        toastOptions={{
          style:{
            background: "#000000",
            color: "#fff",
          }
        }}
        />
        <SanityLive/>
      </body>
    </html>
    </ClerkProvider>
  );
}




